"""Primeira migração

Revision ID: 65d85ee17559
Revises: 
Create Date: 2023-08-04 15:14:28.380072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d85ee17559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.String(length=555), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomeUsuario', sa.String(length=18), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=555),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=555),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
        batch_op.drop_column('nomeUsuario')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
